checksumBehavior: update

compressionLevel: mixed

enableGlobalCache: false

logFilters:
  - code: YN0002
    level: error
  - code: YN0086
    level: error

packageExtensions:
  "@nivo/core@*":
    dependencies:
      "@nivo/tooltip": 0.81.0
      prop-types: "*"
  "@nivo/legends@*":
    dependencies:
      "@nivo/colors": 0.81.0
      d3-scale: "*"

supportedArchitectures:
  cpu:
    - x64
    - x86
    - arm
    - ia32
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-remote.cjs
