compressionLevel: mixed
checksumBehavior: update

enableGlobalCache: false

packageExtensions:
  "@nivo/core@*":
    dependencies:
      prop-types: "*"
      '@nivo/tooltip': '0.81.0'
  '@nivo/legends@*':
    dependencies:
      d3-scale: '*'
      '@nivo/colors': '0.81.0'

logFilters:
  - code: YN0002
    level: error
  - code: YN0086
    level: error

plugins:
  - checksum: 6eb81553ae3ea529e9d6f0a1003bc923201d7e01e6ae70264b3226bc252bc547e42ba24154a740ea00ca73907b6a57abc29a7f83c84e682f083babb465155021
    path: .yarn/plugins/@yarnpkg/plugin-tsconfig-workspaces.cjs
    spec: .yarn/standalone/tsconfig-workspaces/bundles/@yarnpkg/plugin-tsconfig-workspaces.js

supportedArchitectures:
  cpu:
    - x64
    - x86
    - arm
    - ia32
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.0.0-rc.48.cjs
