plugins:
  - checksum: 4919ac5fb7490b0a97487395d82e0d2c3097d7115b47ec98fc67ead80ad5c5d1e25cb0f2b22de1c2a77a83aec82ba39540b19c4d8ee32bfb628653342cae0533
    path: .yarn/plugins/@yarnpkg/plugin-tsconfig-workspaces.cjs
    spec: .yarn/standalone/tsconfig-workspaces/bundles/@yarnpkg/plugin-tsconfig-workspaces.js

yarnPath: .yarn/releases/yarn-4.0.0-rc.48.cjs

enableGlobalCache: false
