services:
  yarn:
    image: node:19
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn
    profiles: [ ]
  api-dev:
    image: node:19
    working_dir: /workspace
    volumes:
      - ./:/workspace
    environment:
      - PORT=8000
      - SUPABASE_URL=https://jopajmdkkjcksytoleoq.supabase.co
      - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvcGFqbWRra2pja3N5dG9sZW9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTA3OTAwNTQsImV4cCI6MjAwNjM2NjA1NH0.ncqCsQSn1Rch4R4QAE1KPXBv_xDj7l0eb3zSAlT-mUY
      - CORS_ORIGIN=["http://localhost:5173"]
      - ROLE_GUARD_TOKEN=MTEzNTQ4MTUxMDY5MTA4NjQwNg.GeAT7r.h_7crCNl4Mm7vFconZGMooLWxb25nA16dbF47s
      - PASS_ROLE_ID=1155617925076627548
      - API_URL=http://localhost:8000/
    entrypoint: yarn workspace @api/entrypoint dev
    ports:
      - 8000:8000
    depends_on:
      yarn:
        condition: service_completed_successfully
    profiles: [ 'dev' ]
  client-dev:
    image: node:19
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn workspace @app/entrypoint dev
    environment:
      - SUPABASE_URL=https://jopajmdkkjcksytoleoq.supabase.co
      - SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvcGFqbWRra2pja3N5dG9sZW9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTA3OTAwNTQsImV4cCI6MjAwNjM2NjA1NH0.ncqCsQSn1Rch4R4QAE1KPXBv_xDj7l0eb3zSAlT-mUY
      - PUBLIC_URL=https://localhost:5173/
    ports:
      - 5173:5173
    depends_on:
      yarn:
        condition: service_completed_successfully
      api-dev:
        condition: service_started
    profiles: [ 'dev' ]
